#! /bin/sh
sxhkd &

# X
xsetroot -cursor_name left_ptr
xset r rate 190 60

# Startup
pkill compton
compton --backend glx --no-fading-openclose --vsync --sw-opti &
nitrogen --set-scaled ~/Pictures/stag.png
pgrep clipmenud || ~/bin/clipmenud &
pkill dunst; dunst &
/home/$USER/.config/polybar/launch.sh
pgrep bspswallow || ~/.config/bspwm/bspswallow &
# polybar wm-restack = bspwm
# chmod weather launch etc
# chmod pulseaudio-control,bash
# chmod polybarscriptsrofi calendar
# https://github.com/adi1090x/rofi/tree/master/fonts
# pip install ueberzug
# sudo apt insatll mpv
# Source Code for Powerline (rofi)
# Source Code Pro
# FontAwesome (polybar)
# ~/.Xmodmap
# xdotool
#sudo add-apt-repository ppa:numix/ppa
#sudo apt update
#sudo apt install numix-icon-theme-circleA
# svg w rangerzzze imagemagick
# vscode zeby dzialal prawy alt "keyboard.dispatch":"keyCode"

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        4
bspc config window_gap          10
bspc config bottom_padding      0
bspc config top_padding         0


bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config click_to_focus       true
bspc config focus_follows_pointer   true

bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# bspc rule -a Toolkit:Firefox -o state=floating rectangle=800x500+700+100 sticky=on
bspc config external_rules_command ~/.config/bspwm/external-rules.bash
bspc rule -a Pavucontrol state=floating sticky=on rectangle=500x400+1246+25
# bspc rule -a dropdown sticky=on state=floating hidden=on
# alacritty --class dropdown --command "/usr/bin/zsh" &
